### ISSUE TITLE
Crash when interacting with jetpack block

### ISSUE THREAD

**Issue by Xanth27** [PssbleTrngle/CreateJetpack#142]
### What happened?

Interacting with the jetpack when it is placed down crashes the server. This same issue isn't encountered with the base create backtanks, only with jetpacks. When loading the server back up, I had to manually mine the jetpack instead of right clicking it(which caused the crash) upon picking the jetpack up, all enchantments were missing, and the name was gone too. so the NBT data was removed. I've attached the server crash report, and the same crash occurring in singleplayer too
[crash-2024-12-13_12.09.12-server.txt](https://github.com/user-attachments/files/18126160/crash-2024-12-13_12.09.12-server.txt)
[crash-2024-12-13_12.12.23-client.txt](https://github.com/user-attachments/files/18126166/crash-2024-12-13_12.12.23-client.txt)

I tested it with a fresh install too. Here is that crash report on a singleplayer world. This is only running Create and Create Jetpack mod
[crash-2024-12-13_12.24.22-server.txt](https://github.com/user-attachments/files/18126248/crash-2024-12-13_12.24.22-server.txt)

### Loader

fabric

### Mod Version

4.2.1

### Minecraft Version

1.20

### Relevant log output

```Shell
Time: 2024-12-13 12:09:12
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.class_2499 com.simibubi.create.content.equipment.armor.BacktankBlockEntity.getEnchantmentTag()'
	at knot//com.possible_triangle.create_jetpack.block.JetpackBlock$getCloneItemStack$enchants$1.invoke(JetpackBlock.kt:27)
	at knot//com.possible_triangle.create_jetpack.block.JetpackBlock$getCloneItemStack$enchants$1.invoke(JetpackBlock.kt:27)
	at knot//com.possible_triangle.create_jetpack.block.JetpackBlock.getCloneItemStack$lambda$1(JetpackBlock.kt:27)
	at java.base/java.util.Optional.map(Optional.java:260)
	at knot//com.possible_triangle.create_jetpack.block.JetpackBlock.method_9574(JetpackBlock.kt:27)
	at knot//com.simibubi.create.content.equipment.armor.BacktankBlock.method_9534(BacktankBlock.java:178)
	at knot//net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at knot//net.minecraft.class_3225.method_14262(class_3225.java:343)
	at knot//net.minecraft.class_3244.method_12046(class_3244.java:1140)
	at knot//net.minecraft.class_2885.method_12547(class_2885.java:34)
	at knot//net.minecraft.class_2885.method_11054(class_2885.java:8)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:22)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:156)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:130)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at knot//net.minecraft.class_1255.method_18857(class_1255.java:139)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Xanth27** [comment]
Just did some further testing, this issue is only occouring with the recent update to the Create Mod. Downgrading Create to F fixed the issue. So it seems Jetpack is currently incompatible with J on fabric anyways.

**Comment by XTerminator01** [comment]
We are having the same problem on our server too. We are using the Create 1.20.1 v0.5.1.j Patch 3 version on a 1.20.1 Quilt Server. Picking up the jetpack by sneaking and right-clicking with a wrench works okay, only the NBT data is missing, but normal right-clicking crashes the server.

**Comment by PssbleTrngle** [comment]
Yeah 0.5.1.j is not really supported yet, will need to release a new build for that

**Comment by MrwoofGaming** [comment]
im having the same issue when i pick up the jetpack by right clicking it it chrashes me and the server instanly
also its not keeping enchantments when mined back up

**Comment by uberswe** [comment]
Seems to be fixed by https://github.com/PssbleTrngle/CreateJetpack-Fabric/commit/f4f628870d134d03635dca31ea0b8360f34f3931

Hopefully this will be published soon

**Comment by PssbleTrngle** [comment]
I have released a new version with support for the new create build that should hopefully fix this issue, if it still persists feel free to reopen this

**Comment by BonesharkTV** [comment]
Hi, I have the same Problem on Forge, but it is when i place it, I used the newest version of the mod, and tried all the older versions, but it still crashed, pls fix, my whole modpack is broken:(

**Comment by PssbleTrngle** [comment]
> Hi, I have the same Problem on Forge, but it is when i place it, I used the newest version of the mod, and tried all the older versions, but it still crashed, pls fix, my whole modpack is broken:(

Hi, could you send me your crash log, or probably better create a new issue with your log attached, will look into it

**Comment by BonesharkTV** [comment]
Sorry already fixed it, was due to an outdated version of Jade Addons:)
