### ISSUE TITLE
Server crashing after 1.2.0 update

### ISSUE THREAD

**Issue by Ks-Proj** [PssbleTrngle/CreateJetpack#15]
### What happened?

Server crashes on start up after updating this mod to 1.2.0 from 1.1.1, the server only contains create, this mod, JEI and Kotlin.

### Mod Version

1.2.0

### Minecraft Version

1.18

### Forge Version

40.1.73

### Relevant log output

```shell
[11:39:15] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[11:39:15] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        Index: 2
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$4197/0x000000080160a390@90852b1
                2: net.minecraftforge.eventbus.EventBus$$Lambda$4197/0x000000080160a390@223b3874
                3: ASM: class com.simibubi.create.content.curiosities.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.60/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at TRANSFORMER/create_jetpack@1.2.0/com.possible_triangle.create_jetpack.network.ControlManager.onTick(ControlManager.kt:98)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@40.1.60/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:860)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_8119_(Player.java:208)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_129483_(Connection.java:245)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
        at java.base/java.lang.Thread.run(Thread.java:833)

Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.60.jar%2317!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
        at com.possible_triangle.create_jetpack.network.ControlManager.onTick(ControlManager.kt:98) ~[create_jetpack-1.2.0.jar%2345!/:1.2.0] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:860) ~[forge-1.18.2-40.1.60-universal.jar%2359!/:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:208) ~[server-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        ... 9 more

[11:39:15] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[11:39:15] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        Index: 2
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$4197/0x000000080160a390@90852b1
                2: net.minecraftforge.eventbus.EventBus$$Lambda$4197/0x000000080160a390@223b3874
                3: ASM: class com.simibubi.create.content.curiosities.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.60/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at TRANSFORMER/create_jetpack@1.2.0/com.possible_triangle.create_jetpack.network.ControlManager.onTick(ControlManager.kt:98)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@40.1.60/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:860)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_8119_(Player.java:208)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_129483_(Connection.java:245)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by atzelpool** [comment]
I also had that problem with client server. Can a query be used at some point in a backpack slot to use with other mods?

**Comment by PssbleTrngle** [comment]
Oh man I hate Client-Only classes. I'll release a hotfix later today

**Comment by PssbleTrngle** [comment]
> I also had that problem with client server. Can a query be used at some point in a backpack slot to use with other mods?

What do you mean by that?

**Comment by atzelpool** [comment]
If it seems that the client can use it the same way on the server but when connecting it gives the error, and if for example there is the space mod I don't remember the name at the moment but it would be very useful to be able to use the jetpack as a backpack or for those other mods that use effects when having full armor.

**Comment by PssbleTrngle** [comment]
Ok, but the backpack slot thing is an entirely different issue/feature request, so I'll create a new one for that

**Comment by atzelpool** [comment]
thanx your mod is the best
