### ISSUE TITLE
Not working with newest Create version (0.5.0g)

### ISSUE THREAD

**Issue by DerCommander323** [PssbleTrngle/CreateJetpack#41]
### What happened?

After updating Create from 0.5.0f to 0.5.0g, the mod causes Minecraft to fail loading. This is probably due to Create changing something in their Registrate code, as seen [here.](https://github.com/Creators-of-Create/Create/commit/131c9a5479ff29dd4135d64cd182de5cb12acaef#diff-5b1ab847321299001d2b39792fd65aee5c8d80581928ed1a3020cd41ecf9dbedL173)

### Mod Version

create_jetpack-1.4.1

### Minecraft Version

1.18

### Forge Version

40.1.86

### Relevant log output

```shell
[15Dec2022 20:44:37.724] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: create_jetpack, class com.possible_triangle.create_jetpack.CreateJetpackMod
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.86.jar%23292!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.86.jar%23291!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.Create.registrate()'
	at com.possible_triangle.create_jetpack.Content.<clinit>(Content.kt:118) ~[create_jetpack-1.4.1.jar%23105!/:1.4.1]
	at com.possible_triangle.create_jetpack.CreateJetpackMod.<init>(CreateJetpackMod.java:17) ~[create_jetpack-1.4.1.jar%23105!/:1.4.1]
	... 14 more
```

**Comment by PssbleTrngle** [comment]
Should be fixed in version 1.4.2
