### ISSUE TITLE
Kick on Join 

### ISSUE THREAD

**Issue by patrickhere** [PssbleTrngle/CreateJetpack#62]
### What happened?

When joining my server, the player gets "Internal Server Error" and the server kicks them. Listed below is the output that the server log has, and then I've attached the modlist on client/server side (server side removes the client side only mods). 
Removing the mod from both server & client allows them to join with no issues.

Running 1.19.2, wasn't listed below as an option.
[current-modlist-3.txt](https://github.com/PssbleTrngle/CreateJetpack/files/11585343/current-modlist-3.txt)

### Mod Version

create_jetpack-3.1.0.jar

### Minecraft Version

None

### Forge Version

43.2.11

### Relevant log output

```shell
[17:28:47] [Server thread/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[17:28:47] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        Index: 5
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: NORMAL
                3: ASM: me.paulf.fairylights.server.ServerEventHandler@67d919ef onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: se.mickelus.tetra.effect.ItemEffectHandler@55eb09e1 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: net.minecraftforge.eventbus.EventBus$$Lambda$4186/0x0000000801b048d0@73c4f61c
                6: net.minecraftforge.eventbus.EventBus$$Lambda$4186/0x0000000801b048d0@48c05db1
                7: net.minecraftforge.eventbus.EventBus$$Lambda$4186/0x0000000801b048d0@4a8a64f4
                8: ASM: class com.hollingsworth.arsnouveau.common.potions.GravityEffect entityTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: class com.hollingsworth.arsnouveau.common.event.ManaCapEvents onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                10: ASM: class com.hollingsworth.arsnouveau.common.event.ManaCapEvents playerOnTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                11: ASM: class com.hollingsworth.arsnouveau.common.event.LightEvents onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: class com.simibubi.create.content.equipment.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: vazkii.quark.content.building.module.HollowLogsModule@73fed873 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: vazkii.quark.content.management.module.AutomaticToolRestockModule@7d890cda onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: vazkii.quark.content.tools.module.PathfinderMapsModule@117dd0b6 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: vazkii.quark.content.tools.module.ColorRunesModule@2ce657c5 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                17: ASM: vazkii.quark.content.tweaks.module.GrabChickensModule@1cd14609 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                18: ASM: vazkii.quark.content.tweaks.module.EnhancedLaddersModule@52072b79 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                19: ASM: vazkii.quark.content.tweaks.module.CompassesWorkEverywhereModule@50b82213 onUpdate(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: ASM: vazkii.quark.content.tweaks.module.CampfiresBoostElytraModule@35338626 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                21: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                22: ASM: air onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                23: net.minecraftforge.eventbus.EventBus$$Lambda$4186/0x0000000801b048d0@3caea9b3
                24: net.minecraftforge.eventbus.EventBus$$Lambda$4186/0x0000000801b048d0@680ecc2c
                25: net.minecraftforge.eventbus.EventBus$$Lambda$4186/0x0000000801b048d0@22e92949
                26: LOW
                27: ASM: se.mickelus.tetra.items.forged.VibrationDebuffer@5b0b6481 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                28: ASM: se.mickelus.tetra.items.modular.impl.toolbelt.booster.TickHandlerBooster@70001029 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                29: LOWEST
                30: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler onGlideTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.11/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/flightlib@1.0.3/com.possible_triangle.flightlib.forge.ForgeEntrypoint.lambda$new$2(ForgeEntrypoint.java:41)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@43.2.11/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:805)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.player.Player.m_8119_(Player.java:216)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129483_(Connection.java:248)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
        at java.base/java.lang.Thread.run(Thread.java:833)

[17:28:47] [Server thread/WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for /24.254.104.30:53103
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:510) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:pluto.mixins.json:player.ServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:ConnectionErrorMixin,pl:mixin:APP:connectivity.mixins.json:NetworkManagerMixin,pl:mixin:APP:pluto.mixins.json:network.flushconsolidation.ConnectionMixin,pl:mixin:APP:pluto.mixins.json:network.pipeline.compression.ConnectionMixin,pl:mixin:APP:pluto.mixins.json:network.pipeline.encryption.ConnectionMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.2.11.jar%2367!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at com.possible_triangle.flightlib.forge.ForgeEntrypoint.lambda$new$2(ForgeEntrypoint.java:41) ~[flightlib-forge-1.0.3.jar%23451!/:1.0.3] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:805) ~[forge-1.19.2-43.2.11-universal.jar%23438!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:216) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tetra.mixins.json:MixinPlayerEntity,pl:mixin:APP:apotheosis.mixins.json:PlayerMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:botania_xplat.mixins.json:PlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:horsecombatcontrols.mixins.json:PlayerMixin,pl:mixin:APP:nochatreports.mixins.json:server.MixinPlayer,pl:mixin:APP:canary.mixins.json:calc.if_else.entity.handle_entity_event.player.PlayerMixin,pl:mixin:APP:canary.mixins.json:calc.if_else.player_slot.PlayerMixin,pl:mixin:APP:bettertridents.common.mixins.json:PlayerMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinPlayer,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23433!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:pluto.mixins.json:player.ServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:A}
        ... 9 more
[17:28:47] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: patrickhere lost connection: Internal server error
[17:28:47] [Server thread/INFO] [minecraft/MinecraftServer]: patrickhere left the game
```

**Comment by HobiJae** [comment]
I have this issue too, I even took out all the mods and kept Create 5.1 and this mod with kotlin and it kicks me out server side but works perfectly fine single player. Same forge version and Minecraft version as well. This happened in the previous version of this mod too. Would deff need and want a fix, this mod is amazing and works well with the new create 5.1 and would really want to use it with friends.

**Comment by PssbleTrngle** [comment]
Oh man I really hate the concept of client-only classes, but I think it should work after @Alex-gnzl PR

**Comment by P4YN-Ki** [comment]
Also getting this issue.

**Comment by Hyperbuss** [comment]
having this issue on 1.19.2 with v3.1.1

**Comment by PssbleTrngle** [comment]
That's pretty weird, are you sure you updated the version on the server & client @Hyperbus02? And if so, which version of forge are you using?

**Comment by PssbleTrngle** [comment]
Feel free to reopen if the problem still exists
