### ISSUE TITLE
Client Crash MC 1.19.2

### ISSUE THREAD

**Issue by tacogerbil** [PssbleTrngle/CreateJetpack#78]
### What happened?

Client crash on 1.19.2 with Create .51c when joining personal Minecraft server.
Minecraft 1.19.2 with Fabric Loader 0.14.22

[2023-08-28-6.log](https://github.com/PssbleTrngle/CreateJetpack/files/12455605/2023-08-28-6.log)
[crash-2023-08-28_07.10.29-client.txt](https://github.com/PssbleTrngle/CreateJetpack/files/12455624/crash-2023-08-28_07.10.29-client.txt)

### Loader

fabric

### Mod Version

create_jetpack 3.2.3

### Minecraft Version

1.19

### Relevant log output

```Shell
java.lang.NoSuchMethodError: 'net.minecraft.class_1799 com.simibubi.create.content.equipment.armor.BacktankUtil.get(net.minecraft.class_1309)'
	at com.possible_triangle.create_jetpack.item.BrassJetpack.isUsable(BrassJetpack.kt:86)
	at com.possible_triangle.flightlib.init.FlightApiImpl.findActiveJetpack(FlightApiImpl.kt:57)
	at com.possible_triangle.flightlib.logic.JetpackLogic.onTick(JetpackLogic.kt:54)
	at com.possible_triangle.flightlib.fabric.FabricClientEntrypoint.lambda$onInitializeClient$0(FabricClientEntrypoint.java:23)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$cjf000$fabric-lifecycle-events-v1$onStartTick(class_310.java:16468)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by PssbleTrngle** [comment]
Ah nice 5.1.c is out for fabric, will update the mod to fix this
